# 19. Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr= np.array([1,2,3])

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Two Dimensional Array

In [20]:
np.array(my_mat)
# We can know the dimension by checking the number of
# brakcet in the beginning or end

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Instead of casting a list into array,
a mommon way to create a numpy array:

In [10]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2) ## the step is 2

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
# The first number represents the number of rows
# while the second means the columns.
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.linspace(0,5,100)
# the third parameter means how many points we want to have

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [24]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.28241492, 0.86143442, 0.37444704, 0.05138839, 0.88882387])

In [26]:
np.random.rand(5,5)
# 5*5 matrix

array([[0.06879542, 0.29432995, 0.05628708, 0.12717761, 0.84902916],
       [0.14512603, 0.84018434, 0.05764923, 0.70619593, 0.81767069],
       [0.42718665, 0.43977967, 0.02637919, 0.23920432, 0.807315  ],
       [0.89199646, 0.35487846, 0.05246699, 0.00319914, 0.06816352],
       [0.26640974, 0.4202271 , 0.36007168, 0.73966727, 0.94317333]])

In [27]:
np.random.randn(2)
## from a standard normal distributionnp.r

array([ 0.31707033, -0.1464559 ])

In [28]:
np.random.randint(1,100,50)
# low is inclusive while high is exclusive.
# The 3rd paramter is the number of int we want

array([40, 47, 45, 37, 51, 85, 57, 13, 52, 73, 53, 97, 24, 90,  2, 63,  8,
       23, 92, 94, 58, 48, 66, 11, 16, 10, 79, 36,  1, 60, 60, 88, 14, 35,
       14, 35, 63, 50, 66, 31, 24, 98, 78,  1, 23, 83, 64, 84, 63, 53])

In [29]:
arr = np.arange(25)

In [30]:
ranarr= np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([21, 29, 42, 38, 14,  5, 34, 40,  1, 16])

### reshape

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 

In [35]:
ranarr.max()
#ranarr.min()

42

In [36]:
# The location of the max value:
ranarr.argmax()

2

In [37]:
ranarr.argmin()

8

In [39]:
arr.shape

(25,)

In [40]:
arr1 = arr.reshape(5,5)

In [41]:
arr1.shape

(5, 5)

In [42]:
arr.dtype

dtype('int32')

In [43]:
ranarr.dtype

dtype('int32')

# 20. Numpy Indexing and Selection

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[0:5] = 100
#broadcast

In [52]:
    arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr = np.arange(0,11)

## Slice
slice_of_arr is just a view from arr, not a copy. So when we broadcast the slice_of_arr, the arr also changes:

In [54]:
slice_of_arr = arr[0:6]

In [55]:
slice_of_arr[:] = 99

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr_copy = arr.copy()

In [59]:
arr_copy[:] = 199

In [60]:
arr_copy

array([199, 199, 199, 199, 199, 199, 199, 199, 199, 199, 199])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Matrix

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

There are 2 general formats for grabbing elements from an array:
double bracket
single bracket: Recommended! 

In [68]:
#double bracket
arr_2d[0][0]

5

In [69]:
#single bracket format
arr_2d[0,0]

5

In [71]:
# What if I want to select the top right section: 
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Conditional selections:


In [72]:
arr = np.arange(1,11)

In [74]:
res = arr > 5

In [75]:
res.dtype

dtype('bool')

In [76]:
# Use the boolean array res to conditionally select elements from the 
# original array
arr[res]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr>5] 

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr<3]

array([1, 2])

# 21.Numpy Operations

### Array with Array

In [79]:
arr = np.arange(0,11)

In [80]:
arr + 3 # Applies to every element in the array.

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr/arr

<ipython-input-83-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Universal array functions

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [86]:
np.max(arr)

10

In [87]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])